# Generated by Django 5.2.11 on 2026-02-27 07:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollFormula',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=150)),
                ('formula_expression', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payroll_formulas',
                'unique_together': {('company_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=150)),
                ('component_type', models.CharField(max_length=50)),
                ('is_taxable', models.BooleanField(default=False)),
                ('is_pf_applicable', models.BooleanField(default=False)),
                ('is_esi_applicable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'salary_components',
                'unique_together': {('company_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'salary_structures',
                'unique_together': {('company_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salary_structure', models.ForeignKey(db_column='salary_structure_id', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pay_roll.salarystructure')),
            ],
            options={
                'db_table': 'salary_structure_versions',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructureComponentMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'FIXED'), ('PERCENT', 'PERCENT'), ('FORMULA', 'FORMULA')], max_length=50)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formula', models.ForeignKey(blank=True, db_column='formula_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='structure_mappings', to='pay_roll.payrollformula')),
                ('salary_component', models.ForeignKey(db_column='salary_component_id', on_delete=django.db.models.deletion.CASCADE, related_name='structure_mappings', to='pay_roll.salarycomponent')),
                ('salary_structure_version', models.ForeignKey(db_column='salary_structure_version_id', on_delete=django.db.models.deletion.CASCADE, related_name='component_mappings', to='pay_roll.salarystructureversion')),
            ],
            options={
                'db_table': 'salary_structure_component_mappings',
                'ordering': ['display_order', 'created_at'],
                'unique_together': {('salary_structure_version', 'salary_component')},
            },
        ),
    ]
