# Generated by Django 5.2.11 on 2026-02-27 10:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('pay_roll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, related_name='salary_config', to='employees.employee')),
                ('salary_structure_version', models.ForeignKey(db_column='salary_structure_version_id', on_delete=django.db.models.deletion.PROTECT, related_name='employee_salaries', to='pay_roll.salarystructureversion')),
            ],
            options={
                'verbose_name_plural': 'Employee Salaries',
                'db_table': 'employee_salaries',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryComponentDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee_salary', models.ForeignKey(db_column='employee_salary_id', on_delete=django.db.models.deletion.CASCADE, related_name='components', to='pay_roll.employeesalary')),
                ('salary_component', models.ForeignKey(db_column='salary_component_id', on_delete=django.db.models.deletion.CASCADE, to='pay_roll.salarycomponent')),
            ],
            options={
                'db_table': 'employee_salary_component_details',
                'unique_together': {('employee_salary', 'salary_component')},
            },
        ),
    ]
